server:
  port: 8003

# MyBatis配置
mybatis:
    # 搜索指定包别名
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
    mapper-locations: classpath:mapping/*Mapper.xml
    type-aliases-package: com.fan.entity
    # 驼峰命名与数据库_命名 全局配置转换
    configuration:
      map-underscore-to-camel-case: true
#      # 开启SQL日志
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl



spring:
  datasource:
    username: user
    password: pass
    url: jdbc:mysql://1.117.168.162:3306/blog?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
#  security:
#    user:
#      name: admin
#      password: admin

  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      exclude: WEB-INF/**
  freemarker:
    cache: false
  redis:
    host: 127.0.0.1
    port: 6379
    password: ''
    # 连接超时时间
    timeout: 30000


